In [1]:
from copyreg import dispatch_table

from sklearn.datasets import make_classification
from torch.utils.data import DataLoader,Dataset
import torch

In [2]:
x,y = make_classification(
    n_features=2,
    n_samples=10,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42,
)

In [3]:
x

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [4]:
x= torch.tensor(x, dtype=torch.float)
y = torch.tensor(y, dtype=torch.float)

In [5]:
class customdataset(Dataset):
    def __init__(self,features,labels):
        self.features=features
        self.labels=labels
    def __len__(self):
        return self.features.shape[0]
    def __getitem__(self, idx):
        return self.features[idx],self.labels[idx]

In [6]:
dataset = customdataset(x,y)

In [7]:
dataloader = DataLoader(dataset,batch_size=2,shuffle=False)

In [8]:
for batchfeatures ,batchlbels in dataloader:
    print(batchfeatures)

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388]])
tensor([[-2.8954,  1.9769],
        [-0.7206, -0.9606]])
tensor([[-1.9629, -0.9923],
        [-0.9382, -0.5430]])
tensor([[ 1.7273, -1.1858],
        [ 1.7774,  1.5116]])
tensor([[ 1.8997,  0.8344],
        [-0.5872, -1.9717]])
